# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Brewing Methods', folder: 'pages', file: 'brewingmethods.html'}
- {name: 'Coffee Grinders', folder: 'pages', file: 'coffeegrinders.html'}
- {name: 'Coffee Types', folder: 'pages', file: 'coffeetypes.html'}
- {name: 'Coffee Makers', folder: 'pages', file: 'coffeemakers.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: ''}
- {icon: 'facebook', link: ''}
- {icon: 'instagram', link: ''}
- {icon: 'envelope', link: ''}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
